# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.21.0"

gem "tty-table", "~> 0.11.0"

gem "tty-font", "~> 0.5.0"

gem "pastel", "~> 0.7.3"

gem "colorize", "~> 0.8.1"

gem "test-unit", "~> 3.3"

gem "gmail", "~> 0.7.1"

gem "html_massage", "~> 0.5.3"
